// angularcrash/src/app/components/add-task/add-task.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { Task } from 'src/app/TaskInterface';
import { UiService } from 'src/app/services/ui.service';
import { Subscription } from 'rxjs';
@Component({
  selector: 'app-add-task',
  templateUrl: './add-task.component.html',
  styleUrls: ['./add-task.component.css']
})
export class AddTaskComponent implements OnInit {
  @Output() onAddTask: EventEmitter<Task> = new EventEmitter()
  text!: string;
  day!: string;
  reminder: boolean = false;
  showAddTask!: boolean
  subscription!: Subscription
  constructor(private uiService: UiService) {
    this.subscription = uiService.onToggle().subscribe(
      (value => this.showAddTask = value)
    )
   }

  ngOnInit(): void {

  }

  onSubmit(){
    if(!this.text){
      alert('Please add a task')
      return
    }

    const newTask = {
      text: this.text,
      day: this.day,
      reminder: this.reminder
    }

    this.onAddTask.emit(newTask)

    this.text = ""
    this.day = ""
    this.reminder = false
  }

}

<form *ngIf="showAddTask" class="add-form" (ngSubmit)="onSubmit()">
    <div class="form-control">
        <label for="task">Task</label>
        <input type="text" name="text" id="text" [(ngModel)]="text" placeholder="Add Task"/>
    </div>
    <div class="form-control">
        <label for="day">Day & Time</label>
        <input type="text" name="day" id="day" [(ngModel)]="day" placeholder="Add Day & Time"/>
    </div>
    <div class="form-control form-control-check">
        <label for="reminder">Set Reminder</label>
        <input type="checkbox" name="reminder" id="reminder" [(ngModel)]="reminder"/>
    </div>
    <input type="submit" class="btn btn-block" value="Click to Add Task"/>
</form>

// react-beginner-app/src/components/AddTask/AddTask.js
import React from 'react';
import {useState} from "react";
// import PropTypes from 'prop-types';


const AddTask = ({onAdd}) => {
    const [text, setText] = useState('')
    const [day, setDay] = useState('')
    const [reminder, setReminder] = useState(false)

    const onSubmit = (e) => {
        e.preventDefault()

        if(!text){
            alert('Please add a task')
            return
        }

        onAdd({text, day, reminder})

        setText('')
        setDay('')
        setReminder(false)
    }
    return (
      <div>
        <form className={'add-form'} onSubmit={onSubmit}>
            <div className={'form-control'}>
                <label>Task</label>
                <input type={'text'}
                       placeholder={'Add Task'}
                       value={text}
                       onChange={(e) => setText(e.target.value)}
                />
            </div>
            <div className={'form-control'}>
                <label>Day & Time</label>
                <input type={'text'}
                       placeholder={'Add Day & Time'}
                       value={day}
                       onChange={(e) => setDay(e.target.value)}
                />
            </div>
            <div className={'form-control form-control-check'}>
                <label>Set Reminder</label>
                <input type={'checkbox'}
                       checked={reminder}
                       value={reminder} onChange={(e) => setReminder(e.currentTarget.checked)}/>
            </div>
            <input type={'submit'} value={'Save Task'} className={'btn btn-block'}/>
        </form>
      </div>
    )
};

AddTask.propTypes = {};

AddTask.defaultProps = {};

export default AddTask;
